### ISSUE TITLE
reset_starting_levels

### ISSUE THREAD

**Issue by odow** [EPOC-NZ/JADE.jl#37]
This union:
https://github.com/EPOC-NZ/JADE.jl/blob/79b364d8ce6eb64c5d615e970bf881105e85b703/src/structs.jl#L23
causes problems here, because that's a `Symbol` being compared!!!
https://github.com/EPOC-NZ/JADE.jl/blob/79b364d8ce6eb64c5d615e970bf881105e85b703/src/simulate.jl#L148

**Comment by adow031** [comment]
The way this works is that user will only ever set this to true or false, and if it's not specified it will be set to :default. If it's not set by the user, the behaviour will depend on other settings (e.g. steady state). Comparing a symbol and bool hasn't previously caused an error - it just returns false.

**Comment by odow** [comment]
Is the default `false`? Is so, why not make it `false` to start with? What other symbols are supported?

**Comment by adow031** [comment]
The `:default` option will be the same as `false` if the model is steady-state, whereas for a finite-horizon model `:default` will have the same behaviour as `true`. 

The reason for this is that the user may wish to set the option, but we also want to allow the model to choose the more sensible option, so that the user isn't forced to make a choice that they might get wrong (somehow students would always set this incorrectly, before I set up this default option.
