### ISSUE TITLE
Audit sddp_modifications.jl

### ISSUE THREAD

**Issue by odow** [EPOC-NZ/JADE.jl#7]
Much of the code in https://github.com/EPOC-NZ/JADE.jl/blob/main/src/sddp_modifications.jl should be moved into SDDP.jl with appropriate modifications. Ideally, we won't have any SDDP.jl extensions in JADE.jl.

**Comment by odow** [comment]
I have been making progress on this.

Various bits have been removed from JADE:
 * https://github.com/EPOC-NZ/JADE.jl/pull/20
 * https://github.com/EPOC-NZ/JADE.jl/pull/23
 * https://github.com/EPOC-NZ/JADE.jl/pull/27

And upstreamed into SDDP.jl
 * https://github.com/odow/SDDP.jl/pull/535
 * https://github.com/odow/SDDP.jl/pull/547
 * https://github.com/odow/SDDP.jl/pull/549

I still need to get my head around:

https://github.com/EPOC-NZ/JADE.jl/blob/c4621f9fae4f66776f0b4281222450d133c3420b/src/sddp_modifications.jl#L8-L194

**Comment by odow** [comment]
Okay so the motivation for the cut functions is that JADE can nominate a start week. And instead of modifying the graph, we're modifying a bunch of the other bits (e.g., the `initial_node` argument to `InSampleMonteCarlo`, although that is independently useful).

It would have been simpler to create a 52 node graph, and then change the arc between the root node and the graph from `0 => 1` to `0 => start_wk`.

@adow031: if we change the graph, is that bad? Does the discount factor need to go 52 weeks after the start week, or can it always live between weeks 52 and 1?

**Comment by adow031** [comment]
The reason for this isn't because we can change the initial week, but that is taken into account. I don't think that changing the network (arc from the root node) can replicate what we are doing here.

The way that we use the steady-state cuts is to first generate these for 52 weeks with some long-run properties set. We then set up a (possibly) completely different model, perhaps with only 20 weeks with a finite horizon. This will end in one of the weeks from the steady-state, and we want to load those cuts into the final stage.

The indices of the SDDP's cuts are based on the stage of the model, so in order to make things work for JADE, regardless of the starting week used for training the steady-state policy, these are saved with week 1 of the year defined to be stage 1. This means that the cuts can be loaded without any conversion.

This may not be something that can / should be generalised in SDDP.jl.

**Comment by odow** [comment]
Closed by #33. The file is now gone :smile:
